export const RESET_HOME_PAGE = 'RESET_HOME_PAGE';
export const RESET_PRESALE_PAGE = 'RESET_PRESALE_PAGE';
export const RESET_AGORA_PAGE = 'RESET_AGORA_PAGE';
export const RESET_FAQ_PAGE = 'RESET_FAQ_PAGE';
export const RESET_STAKE_PAGE = 'RESET_STAKE_PAGE';
